<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<title>RS commerce</title>
	<link rel="stylesheet" type="text/css" href="skin/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="skin/css/custom.css">
	<script type="text/javascript" src="skin/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="skin/js/jquery_1_11_0.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div class="row menu-top">
			<span class="pull-left col-xs-4"><span class="glyphicon glyphicon-plus"></span>Faça login ou cadastre-se</span>
			<span class="col-xs-4"><span class="glyphicon glyphicon-file"></span>Meu painel</span>
			<div class="pull-right col-xs-4 cart">
				Itens no carrinho<br>
				<span style="font-size: 50px;">2</span>
				<br><span style="line-height: 0;">itens</span>
			</div>
		</div>
		<div class="row header">
			<div class="col-xs-2 pull-left" id="col-logo">
				<img src="skin/images/logo.png" id="logo">
			</div>
			<div class="col-xs-9 pull-right">
				<form class="form-search pesquisa">
					<div class="lupa">
						<img src="skin/images/lupa.png">
					</div>
  					<input type="text" class="form-control" 
  					placeholder="Olá, o que você está procurando hoje?" id="inputInfo1">
  					<input type="submit" class="btn btn-primary" value="Buscar!">
				</form>
			</div>
			<div class="row slogan col-xs-12">
				A tecnologia ao alcance do seu orçamento!
			</div>
		</div>
		<div class="row informativo">
			Promoção de COPA: Durante a Copa do Mundo, frete grátis para compras acima de R$100,00!
		</div>
		<div class="row breadcrumb">
			Você está aqui: RS Commerce > Tecnologia
		</div>
		<div class="row">
			<div class="col-xs-3 menu-esquerda pull-left">
				<div class="row dropdown">
					<div class="menu">
						<span class="glyphicon glyphicon-arrow-right"></span>
						<span class="title">Tecnologia</span>
						<ul>
							<li><a href="#">Câmeras</a></li>
							<li><a href="#">Filmadoras</a></li>
							<li><a href="#">Games</a></li>
							<li><a href="#">Informática</a></li>
						</ul>
					</div>
					<div class="menu">
						<span class="glyphicon glyphicon-arrow-right"></span>
						<span class="title">Cultura</span>
						<ul>
							<li><a href="#">Esportes</a></li>
							<li><a href="#">Lazer</a></li>
							<li><a href="#">Instrumentos musicais</a></li>
							<li><a href="#">Fotos</a></li>
						</ul>
					</div>
				</div>
				<div class="row newsletter">
					<h2><span class="glyphicon glyphicon-arrow-right"></span><span class="title">Newsletter</span></h2>
					Cadastre-se na nossa newsletter
					e tenha 10% de desconto na sua
					próxima compra!<br>
					<input type="email" Placeholder="Digite aqui seu email"><input type="submit" class="btn btn-primary">
				</div>
				<div class="row central-atendimento">
					<h2><span class="glyphicon glyphicon-arrow-right"></span><span class="title">Central de atendimento</span></h2>
					<br><br>
					<span class="glyphicon glyphicon-phone"></span> (42) 3035 0000<br>
					<span class="glyphicon glyphicon-envelope"></span> <label style="font-size: 12px;">atendimento@rscommerce.com.br</label>
				</div>
			</div>
			<div class="col-xs-9 centro">
				<div class="row produtos-categoria">
					<h3><span class="glyphicon glyphicon-arrow-right"><span class="title">Tecnologia</span></h3>
					<ul>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
					</ul>
				</div>
				<div class="row produtos-categoria">
					<ul>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
					</ul>
				</div>
				<div class="row produtos-categoria">
					<ul>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
					</ul>
				</div>
				<div class="row produtos-categoria">
					<ul>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
						<li>
							<span class="name">IPhone 5S</span>
							<img src="skin/images/product.jpg" class="product"><br>
							<span class="de">De: R$5000,00</span><br>
							<span class="por">Por: R$2500,00</span>
						</li>
					</ul>
				</div>
				<div class="row pagination">
					<span>Página 
						<a href="#"><b>1</b></a> - 
						<a href="#">2</a> - 
						<a href="#">4</a> ..
						<a href="#">10</a>
					</span>
				</div>
			</div>
		</div>
		<div class="row search">
			<form class="form-search pesquisa">
				<div class="lupa">
					<img src="skin/images/lupa.png">
				</div>
					<input type="text" class="form-control" 
					placeholder="Ainda não achou o que procurava? Pesquise aqui!" id="inputInfo1">
					<input type="submit" class="btn btn-primary" value="Buscar!">
			</form>
		</div>
		<div class="row footer">
			<div class="col-xs-4 formas-pagamento">
				<h2><span class="title">Formas de pagamento</span></h2>
				<img src="skin/images/metodos-pagamento.png" style="width: 100%;">
			</div>
			<div class="col-xs-4 redes-sociais">
				<h2><span class="title">Redes sociais</span></h2>
				<img src="skin/images/redes-sociais.png" style="width: 100%;">
			</div>
			<div class="col-xs-4 selos">
				<h2><span class="title">Selos</span></h2>
				<img src="skin/images/selos-seguranca.png" style="width: 100%;">
			</div>
		</div>
		<div class="row creditos" style="text-align: center;">
			Desenvolvido por Érico Dias Ferreira.
		</div>
	</div>
</body>
</html>