<html lang="pt-br">
<head>
	<meta charset="utf-8">
	<title>RS commerce</title>
	<link rel="stylesheet" type="text/css" href="skin/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="skin/css/custom.css">
	<script type="text/javascript" src="skin/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="skin/js/jquery_1_11_0.min.js"></script>
</head>
<body>
	<div class="container-fluid">
		<div class="row menu-top">
			<span class="pull-left col-xs-4"><span class="glyphicon glyphicon-plus"></span>Faça login ou cadastre-se</span>
			<span class="col-xs-4"><span class="glyphicon glyphicon-file"></span>Meu painel</span>
			<div class="pull-right col-xs-4 cart">
				Itens no carrinho<br>
				<span style="font-size: 50px;">2</span>
				<br><span style="line-height: 0;">itens</span>
			</div>
		</div>
		<div class="row header">
			<div class="col-xs-2 pull-left" id="col-logo">
				<img src="skin/images/logo.png" id="logo">
			</div>
			<div class="col-xs-9 pull-right">
				<form class="form-search pesquisa">
					<div class="lupa">
						<img src="skin/images/lupa.png">
					</div>
  					<input type="text" class="form-control" 
  					placeholder="Olá, o que você está procurando hoje?" id="inputInfo1">
  					<input type="submit" class="btn btn-primary" value="Buscar!">
				</form>
			</div>
			<div class="row slogan col-xs-12">
				A tecnologia ao alcance do seu orçamento!
			</div>
		</div>
		<div class="row" style="margin-top: 10px; margin-bottom: 10px;">
			<div class="col-xs-3 menu-esquerda pull-left">
				<div class="row dropdown">
					<div class="menu">
						<span class="glyphicon glyphicon-arrow-right"></span>
						<span class="title">Tecnologia</span>
						<ul>
							<li><a href="#">Câmeras</a></li>
							<li><a href="#">Filmadoras</a></li>
							<li><a href="#">Games</a></li>
							<li><a href="#">Informática</a></li>
						</ul>
					</div>
					<div class="menu">
						<span class="glyphicon glyphicon-arrow-right"></span>
						<span class="title">Cultura</span>
						<ul>
							<li><a href="#">Esportes</a></li>
							<li><a href="#">Lazer</a></li>
							<li><a href="#">Instrumentos musicais</a></li>
							<li><a href="#">Fotos</a></li>
						</ul>
					</div>
				</div>
				<div class="row newsletter">
					<h2><span class="glyphicon glyphicon-arrow-right"></span><span class="title">Newsletter</span></h2>
					Cadastre-se na nossa newsletter
					e tenha 10% de desconto na sua
					próxima compra!<br>
					<input type="email" Placeholder="Digite aqui seu email"><input type="submit" class="btn btn-primary">
				</div>
				<div class="row central-atendimento">
					<h2><span class="glyphicon glyphicon-arrow-right"></span><span class="title">Central de atendimento</span></h2>
					<br><br>
					<span class="glyphicon glyphicon-phone"></span> (42) 3035 0000<br>
					<span class="glyphicon glyphicon-envelope"></span> <label style="font-size: 12px;">atendimento@rscommerce.com.br</label>
				</div>
			</div>
			<div class="col-xs-9 centro">
				<form class="form">
					<span class="glyphicon glyphicon-arrow-right"></span>
					<span class="title">Contate-nos</span><br><br>
					Tem alguma sugestão, dúvida, ou simplesmente quer bater um papo conosco? contate-nos por e-mail utilizando o formulário abaixo!<br><br>
					<label>Nome *</label><br>
					<input value="Digite aqui seu nome" class="form-control"><br>
					<label>E-mail *</label><br>
					<input type="email" value="Digite aqui seu e-mail" class="form-control"><br>
					<label>Telefone</label><br>
					<input type="tel" value="Digite aqui seu telefone" class="form-control"> <br>
					<label>Mensagem *</label><br>
					<textarea class="form-control">Digite aqui sua mensagem</textarea><br>
					<input type="submit" class="btn btn-success">
				</form>
			</div>
		</div>
		<div class="row footer">
			<div class="col-xs-4 formas-pagamento">
				<h2><span class="title">Formas de pagamento</span></h2>
				<img src="skin/images/metodos-pagamento.png" style="width: 100%;">
			</div>
			<div class="col-xs-4 redes-sociais">
				<h2><span class="title">Redes sociais</span></h2>
				<img src="skin/images/redes-sociais.png" style="width: 100%;">
			</div>
			<div class="col-xs-4 selos">
				<h2><span class="title">Selos</span></h2>
				<img src="skin/images/selos-seguranca.png" style="width: 100%;">
			</div>
		</div>
		<div class="row creditos" style="text-align: center;">
			Desenvolvido por Érico Dias Ferreira.
		</div>
	</div>
</body>
</html>